### ISSUE TITLE
[Epic] 기여작 삭제 구현하기

### ISSUE THREAD

**Issue by sunghyuki** [JNU-econovation/collusic-new#10]
* [x]   (채택이 안 된 경우) 기여작 삭제 API 구현하기
* [x]   (채택이 된 경우) 삭제 안 되게 예외사항 처리하기
-> #73 
* [ ]   기여작 삭제 테스트 코드 작성하기
